version: '3'
services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cars
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./sql/DATABASE-setup.sql:/docker-entrypoint-initdb.d/DATABASE-setup.sql
    command: --init-file /docker-entrypoint-initdb.d/DATABASE-setup.sql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

  app:
    build:
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    container_name: CarsApi
    depends_on:
      - mysqldb
      - user-consumer-service
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/cars?useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SERVER_PORT=8082
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest

  user-consumer-service:
    build:
      context: ./UserConsumerService
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    container_name: UserConsumerService
    depends_on:
      - mysqldb
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/cars?useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SERVER_PORT=8081
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
